### ISSUE TITLE
Script initialization is broken

### ISSUE THREAD

**Issue by salgo60** [Abbe98/human-readable-kulturarvsdata#1]
Thanks for this.... 

looks like it worked for me when  
I [changed](https://www.wikidata.org/w/index.php?title=User:Salgo60/common.js&oldid=787205786
)  

>>  $(window).on('load', function() {

to

>>$(document).ready ( function () {

**Comment by Abbe98** [comment]
I think that became broken, last summer thanks for noticing I will update the script!

**Comment by salgo60** [comment]
Maybe we should have it as a script in Wikidata see https://www.wikidata.org/wiki/User:Salgo60/kulturarvsdata.js

==> you just add 

importScript('User:Salgo60/kulturarvsdata.js');

and/or make it part of https://www.wikidata.org/wiki/Wikidata:Tools/Enhance_user_interface/sv

I saw afterwards that you added a [comment 15:58, 27 January 2017](https://www.wikidata.org/w/index.php?title=Property_talk%3AP1260&type=revision&diff=438590435&oldid=436661023) that you had this script but it took me 1 year to find it...

**Comment by Abbe98** [comment]
Possibly, I have hopes that we will start to point the URIs automatically to Kringla for humans during the first half of next year. I think having obsolete Javascript for users on Wikidata is an terrible idea and it should definitely not origin from a user page (for maintainability reasons).

I also think that the WMF is getting closer to change how Userscripts work so it might break(again).

**Comment by Abbe98** [comment]
On another note, I intend to drop P1260 support for /html/ links, we does not consider such links stable and we change them anyway.

**Comment by salgo60** [comment]
Ok it feels like a mess. I guess what we see is the weakness of Wikidata that no one feels ownership of the data in Wikidata and no good description exists of future plans/status of this data....

**Comment by Abbe98** [comment]
I disagree and I think that the WMF vision for Wikidata is clear and clearly stated.

However Userscripts and Gadgets are a weakness but that's changing.

**Comment by salgo60** [comment]
ok not strongly disagree as [last time ](https://www.wikidata.org/wiki/Wikidata:Property_proposal/Libris-URI) ;-)
